preset: laravel

enabled:
 - ereg_to_preg
 - modernize_types_casting
 - no_php4_constructor
 - php_unit_construct
 - php_unit_strict
 - no_short_echo_tag
 - space_after_semicolon
 - concat_with_spaces
 - no_extra_block_blank_lines
 - no_empty_comment
 - phpdoc_order
 - phpdoc_add_missing_param_annotation

disabled:
 - phpdoc_no_package
 - whitespace_after_comma_in_array
 - space_after_semicolon
 - not_operator_with_successor_space
 - psr4
 - simplified_null_return
 - unalign_equals
 - trailing_comma_in_multiline_array
 - concat_without_spaces

finder:
 name:
  - "*.php"
  - "*.pdt"
